export const customThemes = {
    dracula: {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'f8f8f2', background: '282a36' },
            { token: 'invalid', foreground: 'ff5555' },
            { token: 'emphasis', fontStyle: 'italic' },
            { token: 'comment', foreground: '6272a4' },
            { token: 'string', foreground: 'f1fa8c' },
            { token: 'variable', foreground: '50fa7b' },
            { token: 'keyword', foreground: 'ff79c6' },
            { token: 'operator', foreground: 'ff79c6' },
            { token: 'annotation', foreground: 'f1fa8c' },
            { token: 'attribute.name', foreground: '50fa7b' },
            { token: 'attribute.value', foreground: 'f1fa8c' },
            { token: 'constant', foreground: 'bd93f9' },
            { token: 'number', foreground: 'bd93f9' },
            { token: 'type', foreground: '8be9fd' },
            { token: 'class', foreground: '8be9fd' },
            { token: 'function', foreground: '50fa7b' },
        ],
        colors: {
            'editor.background': '#282a36',
            'editor.foreground': '#f8f8f2',
            'editorCursor.foreground': '#f8f8f0',
            'editor.lineHighlightBackground': '#44475a',
            'editor.selectionBackground': '#44475a',
            'editor.inactiveSelectionBackground': '#44475aa0',
        },
    },
    monokai: {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'f8f8f2', background: '272822' },
            { token: 'comment', foreground: '75715e' },
            { token: 'string', foreground: 'e6db74' },
            { token: 'constant', foreground: 'ae81ff' },
            { token: 'keyword', foreground: 'f92672' },
            { token: 'variable', foreground: 'f8f8f2' },
            { token: 'function', foreground: 'a6e22e' },
            { token: 'class', foreground: 'a6e22e' },
            { token: 'type', foreground: '66d9ef' },
        ],
        colors: {
            'editor.background': '#272822',
            'editor.foreground': '#f8f8f2',
            'editorCursor.foreground': '#f8f8f0',
            'editor.lineHighlightBackground': '#3e3d32',
            'editor.selectionBackground': '#49483e',
        },
    },
    'github-dark': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'c9d1d9', background: '0d1117' },
            { token: 'comment', foreground: '8b949e' },
            { token: 'keyword', foreground: 'ff7b72' },
            { token: 'string', foreground: 'a5d6ff' },
            { token: 'constant', foreground: '79c0ff' },
            { token: 'variable', foreground: 'c9d1d9' },
            { token: 'function', foreground: 'd2a8ff' },
            { token: 'class', foreground: 'd2a8ff' },
            { token: 'type', foreground: 'ff7b72' },
        ],
        colors: {
            'editor.background': '#0d1117',
            'editor.foreground': '#c9d1d9',
            'editorCursor.foreground': '#c9d1d9',
            'editor.lineHighlightBackground': '#161b22',
            'editor.selectionBackground': '#1f6feb',
        },
    },
};
