export const customThemes = {
    dracula: {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'f8f8f2', background: '282a36' },
            { token: 'invalid', foreground: 'ff5555' },
            { token: 'emphasis', fontStyle: 'italic' },
            { token: 'comment', foreground: '6272a4' },
            { token: 'string', foreground: 'f1fa8c' },
            { token: 'variable', foreground: '50fa7b' },
            { token: 'keyword', foreground: 'ff79c6' },
            { token: 'operator', foreground: 'ff79c6' },
            { token: 'annotation', foreground: 'f1fa8c' },
            { token: 'attribute.name', foreground: '50fa7b' },
            { token: 'attribute.value', foreground: 'f1fa8c' },
            { token: 'constant', foreground: 'bd93f9' },
            { token: 'number', foreground: 'bd93f9' },
            { token: 'type', foreground: '8be9fd' },
            { token: 'class', foreground: '8be9fd' },
            { token: 'function', foreground: '50fa7b' },
        ],
        colors: {
            'editor.background': '#282a36',
            'editor.foreground': '#f8f8f2',
            'editorCursor.foreground': '#f8f8f0',
            'editor.lineHighlightBackground': '#44475a',
            'editor.selectionBackground': '#44475a',
            'editor.inactiveSelectionBackground': '#44475aa0',
        },
    },
    monokai: {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'f8f8f2', background: '272822' },
            { token: 'comment', foreground: '75715e' },
            { token: 'string', foreground: 'e6db74' },
            { token: 'constant', foreground: 'ae81ff' },
            { token: 'keyword', foreground: 'f92672' },
            { token: 'variable', foreground: 'f8f8f2' },
            { token: 'function', foreground: 'a6e22e' },
            { token: 'class', foreground: 'a6e22e' },
            { token: 'type', foreground: '66d9ef' },
        ],
        colors: {
            'editor.background': '#272822',
            'editor.foreground': '#f8f8f2',
            'editorCursor.foreground': '#f8f8f0',
            'editor.lineHighlightBackground': '#3e3d32',
            'editor.selectionBackground': '#49483e',
        },
    },
    'github-dark': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'c9d1d9', background: '0d1117' },
            { token: 'comment', foreground: '8b949e' },
            { token: 'keyword', foreground: 'ff7b72' },
            { token: 'string', foreground: 'a5d6ff' },
            { token: 'constant', foreground: '79c0ff' },
            { token: 'variable', foreground: 'c9d1d9' },
            { token: 'function', foreground: 'd2a8ff' },
            { token: 'class', foreground: 'd2a8ff' },
            { token: 'type', foreground: 'ff7b72' },
        ],
        colors: {
            'editor.background': '#0d1117',
            'editor.foreground': '#c9d1d9',
            'editorCursor.foreground': '#c9d1d9',
            'editor.lineHighlightBackground': '#161b22',
            'editor.selectionBackground': '#1f6feb',
        },
    },
    'night-owl': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'd6deeb', background: '011627' },
            { token: 'comment', foreground: '637777', fontStyle: 'italic' },
            { token: 'string', foreground: 'ecc48d' },
            { token: 'constant', foreground: '82aaff' },
            { token: 'keyword', foreground: 'c792ea' },
            { token: 'variable', foreground: 'd6deeb' },
            { token: 'function', foreground: '82aaff' },
            { token: 'class', foreground: 'ffcb8b' },
            { token: 'type', foreground: 'c792ea' },
            { token: 'number', foreground: 'f78c6c' },
        ],
        colors: {
            'editor.background': '#011627',
            'editor.foreground': '#d6deeb',
            'editorCursor.foreground': '#80a4c2',
            'editor.lineHighlightBackground': '#010e1a',
            'editor.selectionBackground': '#1d3b53',
        },
    },
    'nord': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'd8dee9', background: '2e3440' },
            { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
            { token: 'string', foreground: 'a3be8c' },
            { token: 'constant', foreground: 'b48ead' },
            { token: 'keyword', foreground: '81a1c1' },
            { token: 'variable', foreground: 'd8dee9' },
            { token: 'function', foreground: '88c0d0' },
            { token: 'class', foreground: '8fbcbb' },
            { token: 'type', foreground: '81a1c1' },
            { token: 'number', foreground: 'b48ead' },
        ],
        colors: {
            'editor.background': '#2e3440',
            'editor.foreground': '#d8dee9',
            'editorCursor.foreground': '#d8dee9',
            'editor.lineHighlightBackground': '#3b4252',
            'editor.selectionBackground': '#434c5e',
        },
    },
    'solarized-dark': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: '839496', background: '002b36' },
            { token: 'comment', foreground: '586e75', fontStyle: 'italic' },
            { token: 'string', foreground: '2aa198' },
            { token: 'constant', foreground: 'b58900' },
            { token: 'keyword', foreground: '859900' },
            { token: 'variable', foreground: '839496' },
            { token: 'function', foreground: '268bd2' },
            { token: 'class', foreground: 'b58900' },
            { token: 'type', foreground: 'b58900' },
            { token: 'number', foreground: 'd33682' },
        ],
        colors: {
            'editor.background': '#002b36',
            'editor.foreground': '#839496',
            'editorCursor.foreground': '#839496',
            'editor.lineHighlightBackground': '#073642',
            'editor.selectionBackground': '#073642',
        },
    },
    'one-dark-pro': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'abb2bf', background: '282c34' },
            { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
            { token: 'string', foreground: '98c379' },
            { token: 'constant', foreground: 'd19a66' },
            { token: 'keyword', foreground: 'c678dd' },
            { token: 'variable', foreground: 'e06c75' },
            { token: 'function', foreground: '61afef' },
            { token: 'class', foreground: 'e5c07b' },
            { token: 'type', foreground: 'e5c07b' },
            { token: 'number', foreground: 'd19a66' },
        ],
        colors: {
            'editor.background': '#282c34',
            'editor.foreground': '#abb2bf',
            'editorCursor.foreground': '#528bff',
            'editor.lineHighlightBackground': '#2c313c',
            'editor.selectionBackground': '#3e4451',
        },
    },
    'cobalt2': {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: '', foreground: 'ffffff', background: '193549' },
            { token: 'comment', foreground: '0088ff', fontStyle: 'italic' },
            { token: 'string', foreground: '3ad900' },
            { token: 'constant', foreground: 'ff9d00' },
            { token: 'keyword', foreground: 'ff9d00' },
            { token: 'variable', foreground: 'ffffff' },
            { token: 'function', foreground: 'ffc600' },
            { token: 'class', foreground: 'ffc600' },
            { token: 'type', foreground: '80ffbb' },
            { token: 'number', foreground: 'ff628c' },
        ],
        colors: {
            'editor.background': '#193549',
            'editor.foreground': '#ffffff',
            'editorCursor.foreground': '#ffc600',
            'editor.lineHighlightBackground': '#1f4662',
            'editor.selectionBackground': '#0d3a58',
        },
    },
};
